"""Replay runner publishes canonical envelopes for all three sources."""

from pathlib import Path
from typing import Any

import pytest
from aeropulse_connector_app.runner import replay_all
from aeropulse_connector_sdk.cursor import parse_cursor
from aeropulse_contracts.envelope import KafkaEnvelope, ProcessingMode


def test_replay_all_counts() -> None:
    published: list[tuple[str, KafkaEnvelope]] = []

    def capture(topic: str, envelope: KafkaEnvelope) -> None:
        published.append((topic, envelope))

    counts = replay_all(Path("fixtures"), capture)
    assert counts["cpcb"] == 8  # 6 pollutants + 2 pollutants
    assert counts["firms"] == 2
    # IMD is disabled in config/sources.yaml: it has no public API and no
    # credential, and Open-Meteo already emits the same meteo.v1 contract for
    # the same corridor sites. Running both would double-count weather.
    assert counts["imd"] == 0
    # OpenAQ carries reference-grade ground stations (CPCB CAAQMS via
    # monitor=true), which is the live replacement for the cpcb fixture.
    assert counts["openaq"] == 4
    assert counts["sentinel5p"] == 1
    assert counts["modis"] == 1
    assert counts["cams"] == 1
    assert counts["insat"] == 1
    assert counts["bhuvan"] == 1
    assert counts["icar"] == 1
    assert counts["industry"] == 1
    assert counts["osm"] == 1
    # Open-Meteo's fixture is regenerated by scripts/refresh_openmeteo_fixture.py,
    # so an exact count would break on every refresh. What matters is that it
    # participates at all: it was absent from the runner entirely until the
    # registry made multi-contract sources expressible.
    assert counts["openmeteo"] > 0
    assert all(e.processing_mode == ProcessingMode.BACKFILL for _, e in published)


def test_replay_all_respects_sources_yaml_missing_file(tmp_path: Path) -> None:
    """A missing/unreadable registry must not silently stop ingestion."""
    published: list[tuple[str, KafkaEnvelope]] = []
    counts = replay_all(
        Path("fixtures"),
        lambda topic, env: published.append((topic, env)),
        sources_config=tmp_path / "does-not-exist.yaml",
    )
    assert counts["cpcb"] == 8
    assert counts["osm"] == 1


def test_replay_all_disables_source_via_config(tmp_path: Path) -> None:
    """`config/sources.yaml` is now load-bearing: disabling a source skips it."""
    config = tmp_path / "sources.yaml"
    config.write_text(
        "sources:\n"
        "  - {id: cpcb, enabled: true}\n"
        "  - {id: firms, enabled: false}\n"
        "  - {id: imd, enabled: true}\n"
        "  - {id: sentinel5p, enabled: true}\n"
        "  - {id: modis, enabled: true}\n"
        "  - {id: cams, enabled: true}\n"
        "  - {id: insat, enabled: true}\n"
        "  - {id: bhuvan, enabled: true}\n"
        "  - {id: icar, enabled: true}\n"
        "  - {id: industry, enabled: true}\n"
        "  - {id: osm, enabled: true}\n"
    )
    counts = replay_all(Path("fixtures"), lambda topic, env: None, sources_config=config)
    assert counts["firms"] == 0
    assert counts["cpcb"] == 8


def _only_cpcb_publishes(monkeypatch: pytest.MonkeyPatch, seen: list[Any], records: int = 3):
    """Stub publishing so only cpcb emits, and capture its fetch request.

    Replaces the old ``_replay_cpcb`` monkeypatch: the CPCB raw-archive special
    case is now the generic ``SourceSpec.archive_raw`` path, so there is no
    per-source function left to patch.
    """

    def fake_publish_source(connector, request, publish, mode, raw_uri):
        if getattr(connector, "source_id", None) == "cpcb" or "Cpcb" in type(connector).__name__:
            seen.append(request)
            return records, None
        return 0, None

    monkeypatch.setattr("aeropulse_connector_app.runner._publish_source", fake_publish_source)


def test_replay_all_updates_checkpoint_cursor(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[tuple[str, str]] = []

    class FakeRepo:
        def get_checkpoint(self, source_id: str) -> str | None:
            return "2" if source_id == "cpcb" else None

        def upsert_checkpoint(self, source_id: str, cursor: str) -> None:
            calls.append((source_id, cursor))

    monkeypatch.setattr("aeropulse_connector_app.runner._checkpoint_repository", lambda: FakeRepo())
    requests: list[Any] = []
    _only_cpcb_publishes(monkeypatch, requests)

    counts = replay_all(Path("fixtures"), lambda topic, env: None)

    assert counts["cpcb"] == 3
    # The legacy bare-integer checkpoint is still honoured on read.
    assert parse_cursor(requests[0].cursor).as_offset() == 2
    persisted = dict(calls)
    assert parse_cursor(persisted["cpcb: CPCB"]).as_offset() == 5


def test_replay_all_uses_provider_aware_checkpoint_key(monkeypatch: pytest.MonkeyPatch) -> None:
    class FakeRepo:
        def __init__(self) -> None:
            self.data: dict[str, str] = {"cpcb: CPCB": "2"}

        def get_checkpoint(self, source_id: str) -> str | None:
            return self.data.get(source_id)

        def upsert_checkpoint(self, source_id: str, cursor: str) -> None:
            self.data[source_id] = cursor

    repo = FakeRepo()
    monkeypatch.setattr("aeropulse_connector_app.runner._checkpoint_repository", lambda: repo)
    requests: list[Any] = []
    _only_cpcb_publishes(monkeypatch, requests)

    counts = replay_all(Path("fixtures"), lambda topic, env: None)

    assert counts["cpcb"] == 3
    assert requests[0].provider == "CPCB"
    assert parse_cursor(repo.data["cpcb: CPCB"]).as_offset() == 5


@pytest.mark.parametrize("bad_content", ["not: a: list", "sources: not-a-list"])
def test_replay_all_falls_back_when_config_malformed(tmp_path: Path, bad_content: str) -> None:
    config = tmp_path / "sources.yaml"
    config.write_text(bad_content)
    counts = replay_all(Path("fixtures"), lambda topic, env: None, sources_config=config)
    assert counts["cpcb"] == 8
